apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: jfrog-repo
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  jfrog-repo-job:
    steps:
      - name: checkout-source-code
        uses: cloudbees-io/checkout@v1
      - name: jfrog-actions-workflow-download-file
        uses: cloudbees-io/jfrog-artifactory-download-file@v1.0.15
        with:
          url: ${{ vars.JFROG_URL }}
          username: ${{ vars.JFROG_ACTIONS_USERNAME }}
          password: ${{ secrets.JFROG_ACTIONS_PASSWORD }}
          file-path: ${{ cloudbees.workspace }}/download/jfrog_repo_test.zip
          artifactory-path: example-repo-local/jfrogtest/test.zip
